### ISSUE TITLE
Chyba pri zpracovani TXT

### ISSUE THREAD

**Issue by michalblaha** [tmeinlschmidt/csob-pdf-to-json#1]
Testovano na techto PDF:
[csob1.pdf](https://github.com/tmeinlschmidt/csob-pdf-to-json/files/999180/csob1.pdf)
[csob.pdf](https://github.com/tmeinlschmidt/csob-pdf-to-json/files/999181/csob.pdf)

pdf2text spusteno, overil jsem, ze txt je v UTF-8. 
vygenerovany tyto TXT:
[csob.txt](https://github.com/tmeinlschmidt/csob-pdf-to-json/files/999183/csob.txt)
[csob1.txt](https://github.com/tmeinlschmidt/csob-pdf-to-json/files/999184/csob1.txt)

Spusteni csob2json.rb **na windows** spadne.
Reading csob.txt
csob2json.rb:111:in `block in <main>': incompatible encoding regexp match (UTF-8 regexp with CP852 string) (Encoding::CompatibilityError)
        from csob2json.rb:110:in `each'
        from csob2json.rb:110:in `each_with_index'
        from csob2json.rb:110:in `<main>'

na Mac to probehne ok.
*.txt i *.rb jsou v UTF-8.

**Comment by michalblaha** [comment]
pokud se spusti s parametrem `-EUTF-8`, pak to projde OK.
